# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[4,)" # Require at least 4.x
# License is REQUIRED after 1.16
license='CC-BY-SA'
displayURL='${source}'

[[mods]]
modId="item-converter"
version="${version}"
displayName="${name}"
authors="SettingDust,Yarden-zamir"
description='''
${description}
'''

[[dependencies.item-converter]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.item-converter]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.item-converter]]
modId="kotlin-for-forge"
mandatory=true
versionRange="[4.12.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.item-converter]]
modId="ae2"
mandatory=true
versionRange="[15.4.10,)"
ordering="AFTER"
side="BOTH"

[mc-publish]
modrinth = "9pniJAtk"
curseforge = 1143473
loader = "forge"
mc_version = "1.20.1"
modrinth_slug = "item-converter"
curseforge_slug = "itemconverter"
